mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='myapp'
urlpatterns = [
    path('', views.index),
    path('products/', views.products, name='products'),
    path('products/<int:id>', views.product_detail, name='product_detail'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/update/<int:id>/', views.update_product, name='update_product'),
    path('products/delete/<int:id>/', views.delete_product, name='delete_product'),
]

mysite/mysite/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name='users'
urlpatterns = [
    path('register/', views.register,name='register'),
    
]

mysite/myapp/models.py
from django.db import models

class Product(models.Model):
    def __str__(self) -> str:
        return self.name
    
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

    

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product


def index(request):
    return HttpResponse("Hello World")


def products(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'myapp/index.html', context)


def product_detail(request, id):
    product = Product.objects.get(id=id)
    context = {
        'product': product
    }
    return render(request, 'myapp/detail.html', context)


def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES['upload']
        product = Product(name=name, price=price, desc=desc, image=image)
        product.save()

    return render(request, 'myapp/addproduct.html')

def update_product(request, id):
    
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        if request.FILES.get('upload') : product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/products')
    
    context = {
        'product': product,
    }
    return render(request, 'myapp/updateproduct.html', context)

def delete_product(request, id):
    
    product = Product.objects.get(id=id)
    
    context = {
        'product':product,
    }
    
    if request.method == 'POST':
        product.delete()
        return redirect('/myapp/products')
    return render(request, 'myapp/delete.html', context)

mysite/users/views.py
from django.shortcuts import render
from .forms import NewUserForm

def register(request):
    form = NewUserForm()
    context={
        'form':form,
    }
    return render(request, 'users/register.html',context)

mysite/myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1 class="text-2xl font-bold m-10">➕ Add Product</h1>
<form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Name" type="text" name="name" id="name">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="price" name="price" id="price">
        
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description</label>
        
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="desc" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Image</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add Product" value="Add Product" id="submit">
    </div>
</form>

{% endblock %}

mysite/myapp/templates/myapp/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
        <title>Products</title>
    </head>
    <body>
        <nav class="bg-white shadow-lg">
            <div class="max-w-6xl mx-auto px-4">
                <div class="flex justify-between">
                    <div class="flex space-x-7">
                        <div>
                            <a href="#" class="flex items-center px-2 py-4">
                                <img class="h-16 w-16" src="{% static 'myapp/images/shopping.png' %}" alt="">
                                <span class="text-gray-500 text-lg font-semibold mt-6">Buy&Sell</span>
                            </a>
                        </div>
                        <div class="items-center flex space-x-1">
                            <a href="#" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green">Home</a>
                            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a>
                            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        {% block content %}

        
        {% endblock %}
    </body>
</html>

mysite/myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}

{% block content %}
    <h1 class="text-2xl m-10 font-bold">Delete Product</h1>
    <form method="post" class="bg-white shadow-md m-10 w-2/5 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-gray-700 tezt-sm font-bold mb-2">Are you sure you want to delete this product?</label>
        </div>
        <div class="mb-4">
            <label class="block text-gray-700 tezt-sm font-bold mb-2">{{product.name}}</label>
        </div>
        <div class="mb-4">
            <img class="h-60 w-60 rounded"src="{{product.image.url}}" alt="">
        </div>
        <input class="bg-red-500 text-white px-5 py-2 rounded" type="submit" name="confirm" id="confirm" value="confirm">

        <a class="button bg-green-500 text-white px-5 py-3 rounded" href="{% url 'myapp:products' %}">Cancel</a>
    </form>
{% endblock %}

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}



{% block content %}

<div class="flex p-10 w-full h-200">
    <img class="w-1/3 rounded" src="{{product.image.url}}" alt="">
    <div class="w-2/3 text-xl ml-10 mt-10">
        <div class="mt-5">{{product.name}}</div>
        <div class="mt-5 text-green-500">${{product.price}}</div>
        <div class="mt-5 text-gray-700">{{product.desc}}</div>
    </div>
    
</div>


{% endblock %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block content %}
    <!-- Site hero starts here -->
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div class="sm:text-center lg:text-left">
            <h1 class="text-4xl text-gray-900 font-extrabold sm:text-5xl md:text-6xl">
                <span class="block xl:inline">Premium Products</span>
                <span class="block text-green-500 xl:inline">Non-Premium Prices</span>
            </h1>
            <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality used products across the globe. Free shipping</p>
        </div>
    </main>
    <!-- Site hero ends here -->
    
    <div class="flex mt-5 p-10 justify-center">
        <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent Products</h2>
    </div>    
    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5">
        <!-- Card 1 -->
        {% for product in products %}
    
        <a href="{% url 'myapp:product_detail' product.id %}">
            
            <div class="rounded overflow-hidden shadow-lg">
                <img class="w-full" src="{{product.image.url}}">
                <div class="px-6 py-4">
                    <div class="font-bold text-xl mb-2">
                        {{product.name}}
                    </div>
                    <div class="font-bold text-xl text-green-500 mb-2">
                        ${{ product.price }}
                    </div>
                    <p class="text-gray-700 text-base">
                        {{ product.desc }}
                    <p>
                </div>
            </div>
            
            
            
        
        </a> 
        
        {% endfor %}  
    
    

    </div>
    
    
    
{% endblock %}

mysite/myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1 class="text-2xl font-bold m-10">➕ Update Product</h1>
<form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label  class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
        <input value="{{product.name}}" class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Name" type="text" name="name" id="name">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price</label>
        <input value="{{product.price}}" class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="price" name="price" id="price">
        
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description</label>
        
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="desc" value="{{product.desc}}" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <img class="h-20 w-20" src="{{product.image.url}}" alt="">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Image</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add Product" value="Update Product" id="submit">
    </div>
</form>

{% endblock %}

mysite/users/templates/users/register.html
{{ form }}